logo: # add logo name
title: Libre Know
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Banner settings
video: mountains.jpg # mountains.mp4 # add banner video. Add your video file to the folder video
banner-title: Libre Know # add banner title
banner-desc: Saber Libre # add banner description

# Author settings
author-pic:  # your photo
author-name: Pablo Arak # your name
about-author: # about author
email: pablo.arak.vm@gmail.com # your email
phone:  # your pnone number
website: https://libreknow.org # you website

# Social link
github_url: # add url link
linkedin_url: # add url link
instagram_url: # add url link

# Disqus
discus_identifier: # add your discus identifier

# Newsletter
mailchimp: # add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Tracker
analytics:

# Paginate
paginate: 12
paginate_path: /page:num/

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
